name: "Get & cache dependencies"
description: "Get the dependencies (via npm) and cache them."
inputs:
  caching:
    required: false
    description: This is a turn on or turn on the cahe method
    default: "true"
runs:
  using: composite
  steps:
    - name: Cache
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash
